name: DevOps-Landing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  STACK_FILE: /home/ubuntu/docker/inhouse-projects-2/devopslanding/docker-compose.yml
  CODE_DIR: /home/ubuntu/docker/inhouse-projects-2/devopslanding/app/code

jobs:

  dev-build:
    name: Build (Development)
    runs-on: devopsworkshop
    if: github.ref_name == 'main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rsync source to server & Docker Build
        run: |
          echo "Deploying to https://landing.rezize.com
          sudo rsync -ravz --exclude '.git/' ./ $CODE_DIR/
          sudo docker compose -f $STACK_FILE build --no-cache


  dev-deploy:
    name: Deploy (Development)
    runs-on: devopsworkshop
    needs: dev-build
    if: github.ref_name == 'main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Deploy
        run: |
          echo "Starting Deployment..."
          sudo docker compose -f $STACK_FILE up -d
          sudo docker exec proxy_server nginx -s reload || echo "Failed to reload Nginx"
